---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-green
spec:
  selector:
    matchLabels:
      app: blue-green
      version: v2
  replicas: 1
  template:
    metadata:
      labels:
        app: blue-green
        version: v2
    spec:
      containers:
      - name: blue-green
        image: quay.io/leandroberetta/blue-green
        ports:
        - containerPort: 8080
        env:
        - name: BACKGROUND_COLOR
          value: green
---
apiVersion: v1
kind: Service
metadata:
  name: blue-green
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: blue-green
